### PR TITLE
Keybind feature for quickly changing rooms

### PR DESCRIPTION
**Pull request by deerfarce**
Adds a way to switch rooms using customizable keybinds. Code's a bit messy in some places, so let me know if I need to clean it up. It has a dedicated settings tab and is disabled by default.

Some problems with it:
- I'm not sure how to directly access the methods that switch livestreams, so the plugin now waits for the selection grid in order to load, rather than the general livestream area. The onClick methods are pulled here and stored for later. I'm pretty sure the site always shows the selection grid first, but I don't really like this workaround.
- The site-native numpad method still functions alongside this, but the event propagation should stop if you set numpad binds within this plugin.
- The "Restore Default Binds" button works, but does not _visually_ update the bind list until the settings menu is closed and reopened. Minor issue.
- Unsure how this will behave with different keyboard layouts, especially the default bindings.

### CODE REVIEW

**Comment by maejok-xx** [comment]
Hell yea, good work!  Just do me one favor and remove `./dist/maejok-tools.user.js` and `./package-lock.json` and I will merge this and include it in the next update (which will probably just be to add this). 

Also, I'd like to credit you as a contributor in the About panel, would you me to use your GitHub name and link to it or something else?

**Comment by maejok-xx** [comment]
By the way, I'm not too worried about the issues you listed as this whole thing is kind of just a "use at your own risk" type thing.  As long as it's functioning properly, I don't really care if it has quirks.

Regarding the bind buttons not updating, maybe we could just close the settings panel and reopen it as a workaround.

**Comment by deerfarce** [comment]
> Hell yea, good work! Just do me one favor and remove `./dist/maejok-tools.user.js` and `./package-lock.json` and I will merge this and include it in the next update (which will probably just be to add this).

Done! Also, GitHub name is fine.

The reset button should now visually update the bind buttons too, so that shouldn't be a concern anymore.

**Comment by maejok-xx** [comment]
Actually, one more thing can you add one that toggles Auto Mode?

**Comment by maejok-xx** [comment]
Oh, also, just realized, use [Prettier](https://prettier.io/) please.

**Comment by deerfarce** [comment]
Got it, also added some more additional binds.
The settings modal won't load for you if you used previous versions of this branch because the `binds` object in localstorage won't have the newer bind keys. I don't think anyone coming from the master branch versions will have this issue since they won't have the `binds` map saved at all.

**Comment by maejok-xx** [comment]
Awesome, thanks!

**Comment by maejok-xx** [comment]
Made a couple changes in #45 to handle new/remove keybinds for future updates and to only define the defaults once.

**Comment by maejok-xx** [comment]
should be ready to update, but if you wouldn't mind pulling `master` and testing, I'd appreciate it

**Pull request merged**
